version: '3'

services:

  rails:
    container_name: "kvhtools-rails"
    build: .
    volumes:
      - .:/app:delegated
      - /app/tmp
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 80:3000
