name: Test with Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Build and test with Rake
        env:
          RAILS_ENV: test
          RUBYOPT: '-W:no-deprecated -W:no-experimental'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          touch app/assets/stylesheets/application.css
          bundle exec rails test
